### ISSUE TITLE
Removing a column does not recalculate width

### ISSUE THREAD

**Issue by ChuckFields** [stijlbreuk/vue-split-grid#10]
Removing a column does not recalculate width, however, adding a column does.

[Link to reproduce](https://codesandbox.io/s/vue-split-grid-basic-example-ppic7)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7934525/65542691-a17d6880-dedd-11e9-911d-7d504800596f.gif)

**Comment by ChuckFields** [comment]
The problem seems to be that onChildRemoved only gets called when the :render prop changes, and does not get called if you're using a v-if or v-for on the SplitGridArea.

**Comment by nino-vrijman** [comment]
When columns or rows are being removed from a Grid we need to call the SplitGrid library to reinitialize the grid with the remaining gutters and area's. To my knowledge it is not possible to reliably detect child elements being removed from a component (SplitGrid in our case) when using `v-if` with Vue's reactivity system.

Thats why we introduced two of our own properties to be able to reliably detect child elements being removed from a grid, those properties are [render](https://github.com/stijlbreuk/vue-split-grid#render-boolean) (for which we use `v-if` under the hood) and [show](https://github.com/stijlbreuk/vue-split-grid#show-boolean) (for which we use `v-show` under the hood).

If it is possible to reliably check child elements being removed or hidden when using `v-if` or `v-show` let me know, PRs are also open! I'll be closing this issue for now since it already has been documented.
